//
// Created by huhua on 2022/2/11.
//

#ifndef MH_TOOL_INCLUDE_MHTOOL_MH_GAME_SCENE_CITY_TAOYUANCUN_H_
#define MH_TOOL_INCLUDE_MHTOOL_MH_GAME_SCENE_CITY_TAOYUANCUN_H_
// how to do this?
class TaoYuanCun {

};
#endif //MH_TOOL_INCLUDE_MHTOOL_MH_GAME_SCENE_CITY_TAOYUANCUN_H_
