//
// Created by huhua on 2022/1/23.
//

#ifndef MH_TOOL_INCLUDE_MHTOOL_COMM_POS_INDICATOR_POS_INDICATOR_LANDMARK_H_
#define MH_TOOL_INCLUDE_MHTOOL_COMM_POS_INDICATOR_POS_INDICATOR_LANDMARK_H_
class PosIndicatorLandMark {
};
#endif //MH_TOOL_INCLUDE_MHTOOL_COMM_POS_INDICATOR_POS_INDICATOR_LANDMARK_H_
