//
// Created by huhua on 2022/2/11.
//

#ifndef MH_TOOL_INCLUDE_MHTOOL_MH_GAME_SCENE_TELEPORTATION_NPC_H_
#define MH_TOOL_INCLUDE_MHTOOL_MH_GAME_SCENE_TELEPORTATION_NPC_H_
/**
 * 传送npc
 */
class TeleportationNpc {

};
#endif //MH_TOOL_INCLUDE_MHTOOL_MH_GAME_SCENE_TELEPORTATION_NPC_H_
