//
// Created by huhua on 2022/2/11.
//

#ifndef MH_TOOL_INCLUDE_MHTOOL_MH_GAME_SCENE_CITY_CHANGAN_H_
#define MH_TOOL_INCLUDE_MHTOOL_MH_GAME_SCENE_CITY_CHANGAN_H_

/**
 * 长安
 */
class ChangAn {

};

#endif //MH_TOOL_INCLUDE_MHTOOL_MH_GAME_SCENE_CITY_CHANGAN_H_
